[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 5000
  targetPort = 5000

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optimize asset caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self' https://*.netlify.app;"

# Environment variable placeholders (actual values set in Netlify dashboard)
[context.production.environment]
  NODE_ENV = "production"
  VITE_API_BASE_URL = "/.netlify/functions"

[context.deploy-preview.environment]
  NODE_ENV = "production"
  VITE_API_BASE_URL = "/.netlify/functions"

[context.branch-deploy.environment]
  NODE_ENV = "production"
  VITE_API_BASE_URL = "/.netlify/functions"