[build]
  command = "node netlify-frontend.js"
  publish = "dist"

# Environment variables
[build.environment]
  # Replace with your backend server URL when deployed
  API_URL = "https://your-backend-server-url.com"

# SPA redirect for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200