[build]
  command = "node netlify-build-simple.js"
  publish = "dist/public"
  functions = "dist/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200