services:
  # Web service for the Sill application
  - type: web
    name: sill
    env: node
    plan: free # Adjust as needed: free, starter, standard, etc.
    region: oregon # Choose appropriate region
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    healthCheckPath: /api/stats # Adjust if needed
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 # Render's default port
      # Required Telegram configuration
      - key: TELEGRAM_BOT_TOKEN
        sync: false # This must be set manually for security
      - key: TELEGRAM_CHANNEL_ID
        sync: false # This must be set manually
      - key: TELEGRAM_BOT_ADMIN_PASSWORD
        sync: false # This must be set manually
      - key: ADMIN_PASSWORD
        sync: false # This must be set manually
    autoDeploy: true # Set to false if you prefer manual deployments

# Specify the GitHub repository for deployment
repo: https://github.com/sandy2k25/sill
branch: main # Change if using a different branch